#ifndef ENUM_H
#define ENUM_H

enum ColorIndex { DEFAULT, BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, LIGHT_GRAY, DARK_GRAY, LIGHT_RED, LIGHT_GREEN, LIGHT_YELLOW, 
		LIGHT_BLUE, LIGHT_MAGENTA, LIGHT_CYAN, WHITE};

enum EffectIndex {BOLD, DIM, ITALIC, UNDERLINED, BLINK, INVERTED, HIDDEN, ALL};

#endif
